# Generated by Django 4.2.6 on 2023-10-12 21:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="payment",
            options={"ordering": ("-date_created",)},
        ),
        migrations.RenameField(
            model_name="payment",
            old_name="created",
            new_name="date_created",
        ),
    ]
